const mongoose=require("mongoose")
var TargetSchema=new mongoose.Schema({
    "edited":{
        "type":"Boolean",
        default:false,
    },
    "validated":{
        "type":"Boolean",
        default:false,
    },
    "rid":{
        "type":"Number"
    },
    "vehicle":{
        "type":"Object"
    },
    "plate":{
        "type":"Object"
    },
    "type":{
        "type":"String"
    },
    "speedlimit":{
        "type":"String"
    },
    "violations":{
        "type":"Array"
    },
    "gif":{
        "type":"String"
    },
    "original_image":{
        "type":"String"
    },
    "plot_image":{
        "type":"String"
    },
    "speed":{
        "type":"String"
    },
    "distance":{
        "type":"String"
    },
    "direction":{
        "type":"String"
    },
    "lat":{
        "type":"String"
    },
    "lon":{
        "type":"String"
    },
    "op_name":{
        "type":"String"
    },
    "op_id":{
        "type":"String"
    },
    "dept":{
        "type":"String"
    },
    "location":{
        "type":"String"
    },
    "created_at": {
        "type": "Date"
      }
},{collection:'Records'})
module.exports=mongoose.model("Records",TargetSchema);