const mongoose=require("mongoose")
var TargetSchema=new mongoose.Schema({
    "rstp_url":{
        type:String,
        default:""
    },
    "lidar_url":{
        type:String,
        default:""
    },
    "mode":{
        type:String,
        default:""
    },
    "twowheeler":{
        type:String,
        default:""
    },
    "auto":{
        type:String,
        default:""
    },
    "car":{
        type:String,
        default:""
    },
    "truck":{
        type:String,
        default:""
    },
    "bus":{
        type:String,
        default:""
    },
    "mgv":{
        type:String,
        default:""
    },
    "lat":{
        type:String,
        default:""
    },
    "lon":{
        type:String,
        default:""
    },
    "op_name":{
        type:String,
        default:""
    },
    "op_id":{
        type:String,
        default:""
    },
    "dept":{
        type:String,
        default:""
    },
    "location":{
        type:String,
        default:""
    },
    "logo":{
        type:String,
        default:""
    }
},{collection:'Settings'})
module.exports=mongoose.model("Settings",TargetSchema);